# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

In [3]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [4]:
data.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [22]:
data2 = data.groupby(['CustomerID','ProductName'])['Quantity'].sum()
data2= data2.reset_index()
data2.head()

   CustomerID                    ProductName  Quantity
0          33               Apricots - Dried         1
1          33              Assorted Desserts         1
2          33        Bandage - Flexible Neon         1
3          33  Bar Mix - Pina Colada, 355 Ml         1
4          33         Beans - Kidney, Canned         1

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [26]:
datap = pd.pivot_table(data2, columns='CustomerID', index='ProductName', values='Quantity', fill_value=0)
datap.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0,0,0,0,0,0,0,1,0,0,...,0,25,0,0,0,0,0,0,0,0
"Appetizer - Mini Egg Roll, Shrimp",0,0,0,0,0,0,0,0,0,0,...,25,25,0,0,0,0,0,0,0,0
Appetizer - Mushroom Tart,0,0,0,0,0,0,0,1,0,0,...,25,0,0,0,0,0,0,0,25,0
Appetizer - Sausage Rolls,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,25,25,25,0,25,0
Apricots - Dried,1,0,0,0,1,0,0,0,0,0,...,0,25,0,0,0,0,0,0,0,0

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [34]:
smatrix= squareform(pdist(datap.T, 'euclidean'))
distances = pd.DataFrame(1/(1 + smatrix), index=datap.columns, columns=datap.columns)

distances.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.077421,0.087047,0.081800,0.080634,0.082709,0.074573,0.083020,0.081503,0.080070,...,0.004811,0.004669,0.004412,0.005019,0.004312,0.004515,0.004583,0.004355,0.004167,0.004333
200,0.077421,1.000000,0.078448,0.076435,0.073693,0.075255,0.075956,0.076435,0.077674,0.076923,...,0.004824,0.004681,0.004431,0.005047,0.004311,0.004521,0.004614,0.004367,0.004166,0.004335
264,0.087047,0.078448,1.000000,0.080070,0.081800,0.080350,0.076923,0.080634,0.082100,0.078448,...,0.004822,0.004674,0.004416,0.005035,0.004322,0.004543,0.004595,0.004365,0.004179,0.004333
356,0.081800,0.076435,0.080070,1.000000,0.076435,0.078187,0.075025,0.082403,0.077171,0.075956,...,0.004816,0.004671,0.004416,0.005038,0.004310,0.004526,0.004578,0.004365,0.004175,0.004339
412,0.080634,0.073693,0.081800,0.076435,1.000000,0.078711,0.075025,0.082403,0.078187,0.078448,...,0.004810,0.004702,0.004414,0.005034,0.004318,0.004530,0.004578,0.004367,0.004177,0.004349

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [37]:
similarities = distances[200].sort_values(ascending=False)[1:6].index
similarities

Int64Index([3317, 1072, 3535, 1920, 3909], dtype='int64', name='CustomerID')

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [39]:
similarities_data2 = data2[data2['CustomerID'].isin(similarities)].reset_index(drop=True)
similarities_data2.head()

   CustomerID                        ProductName  Quantity
0        1072  Appetizer - Mini Egg Roll, Shrimp         1
1        1072          Appetizer - Sausage Rolls         1
2        1072             Beans - Kidney, Canned         1
3        1072     Beef - Montreal Smoked Brisket         1
4        1072                Beef - Striploin Aa         1

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [44]:
prod_sim = similarities_data2.groupby('ProductName').sum().sort_values('Quantity', ascending=False)['Quantity']
prod_sim.head()

ProductName
Soup - Campbells Bean Medley       4
Muffin - Carrot Individual Wrap    3
Bay Leaf                           3
Pork - Kidney                      3
Pepper - Black, Whole              3
Name: Quantity, dtype: int64

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [47]:
#combinacion de dataframes
merg = pd.merge(prod_sim, datap[200], on='ProductName').reset_index()
merg.columns = ['ProductName', 'Quantity', 'Purchased']

In [50]:
# Filtar los registros de los clientes que no han comprado el producto
filt = merg.loc[merg['Purchased'] == 0]

In [49]:
filt.head()

                       ProductName  Quantity  Purchased
0     Soup - Campbells Bean Medley         4          0
1  Muffin - Carrot Individual Wrap         3          0
2                         Bay Leaf         3          0
3                    Pork - Kidney         3          0
6                      Wanton Wrap         3          0

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

In [52]:
#diccionario vacio para guardar las recomendaciones
recomm = {customer: [] for customer in set(data['CustomerID'])}

In [53]:
#ciclo para aplicar todos los pasos anteriores pero a cada id de cliente
for c_id in set(data['CustomerID']):
    similarities = distances[c_id].sort_values(ascending=False)[1:6].index
    similarities_data2 = data2[data2['CustomerID'].isin(similarities)].reset_index(drop=True)
    prod_sim = similarities_data2.groupby('ProductName').sum().sort_values('Quantity', ascending=False)['Quantity']
    merg = pd.merge(prod_sim, datap[c_id], on='ProductName').reset_index()
    merg.columns = ['ProductName', 'Quantity', 'Purchased'] 
    filt = merg.loc[merg['Purchased'] == 0]
    recomm[c_id] = list(filt['ProductName'].head())

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [55]:
euclidean_recomm = pd.DataFrame.from_dict(recomm, orient='index').reset_index()
euclidean_recomm.columns = ['CustomerID', 'product1', 'product2', 'product3', 'product4', 'product5']
euclidean_recomm.head(10)

,CustomerID,product1,product2,product3,product4,product5
0,83973,Cocoa Butter,Veal - Slab Bacon,Bandage - Fexible 1x3,Ezy Change Mophandle,Chicken - Wieners
1,59399,"Shrimp - Baby, Warm Water",Knife Plastic - White,Towels - Paper / Kraft,Nantucket - Pomegranate Pear,Snapple - Iced Tea Peach
2,92168,Cup - Translucent 7 Oz Clear,"Veal - Brisket, Provimi,bnls",Snapple Lemon Tea,Spinach - Baby,Pop Shoppe Cream Soda
3,49159,"Pasta - Penne, Rigate, Dry",Cookies - Assorted,Puree - Mocha,Cheese - Parmesan Grated,Cheese - Victor Et Berthold
4,18441,Soupfoamcont12oz 112con,Anchovy Paste - 56 G Tube,Sprouts - Baby Pea Tendrils,"Lemonade - Natural, 591 Ml",Sausage - Breakfast
5,22536,Bacardi Breezer - Tropical,Cheese - Mozzarella,Cheese Cloth No 100,Bread - Italian Roll With Herbs,Bread - Hot Dog Buns
6,86028,Spinach - Baby,Pork - Hock And Feet Attached,Vinegar - Tarragon,Bread Foccacia Whole,Lettuce - Spring Mix
7,75791,Blueberries,Mussels - Cultivated,Vaccum Bag 10x13,Turkey - Oven Roast Breast,Bread - Calabrese Baguette
8,96272,Ecolab - Lime - A - Way 4/4 L,Bread Crumbs - Panko,Guinea Fowl,Sunflower Seed Raw,Bread - English Muffin
9,32785,Cookies - Assorted,Table Cloth 54x72 White,Juice - V8 Splash,Wine - Redchard Merritt,Puree - Passion Fruit

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.

#### correlation

In [56]:
#Cambiado el metodo a correlation
smatrix= squareform(pdist(datap.T, 'correlation'))
distances = pd.DataFrame(1/(1 + smatrix), index=datap.columns, columns=datap.columns)

recomm = {customer: [] for customer in set(data['CustomerID'])}

for c_id in set(data['CustomerID']):
    similarities = distances[c_id].sort_values(ascending=False)[1:6].index
    similarities_data2 = data2[data2['CustomerID'].isin(similarities)].reset_index(drop=True)
    prod_sim = similarities_data2.groupby('ProductName').sum().sort_values('Quantity', ascending=False)['Quantity']
    merg = pd.merge(prod_sim, datap[c_id], on='ProductName').reset_index()
    merg.columns = ['ProductName', 'Quantity', 'Purchased'] 
    filt = merg.loc[merg['Purchased'] == 0]
    recomm[c_id] = list(filt['ProductName'].head())
    
#nuevo dataframe con el metodo nuevo
correlation_recomm = pd.DataFrame.from_dict(recomm, orient='index').reset_index()
correlation_recomm.columns = ['CustomerID', 'product1', 'product2', 'product3', 'product4', 'product5']
correlation_recomm.head(10)

,CustomerID,product1,product2,product3,product4,product5
0,83973,Pastry - Choclate Baked,Flour - Pastry,Puree - Passion Fruit,Lettuce - Spring Mix,Broom - Corn
1,59399,Anchovy Paste - 56 G Tube,Ezy Change Mophandle,Garlic - Peeled,Beans - Wax,Broom - Corn
2,92168,Wiberg Super Cure,Tuna - Salad Premix,Sage - Ground,Apricots Fresh,Beef - Inside Round
3,49159,"Turnip - White, Organic",Peas - Frozen,Lamb - Ground,Beer - Blue,Beef - Ground Medium
4,18441,V8 - Berry Blend,Whmis - Spray Bottle Trigger,Mussels - Cultivated,Ecolab - Lime - A - Way 4/4 L,Milk - 2%
5,22536,Hersey Shakes,Bread Crumbs - Panko,Muffin Batt - Choc Chk,Spinach - Baby,Wine - White Cab Sauv.on
6,86028,Mayonnaise - Individual Pkg,Pail With Metal Handle 16l White,Sunflower Seed Raw,Sausage - Breakfast,"Appetizer - Mini Egg Roll, Shrimp"
7,75791,Peas - Frozen,"Placemat - Scallop, White",Beef - Ground Medium,Milk - 2%,Sausage - Liver
8,96272,Bread - Rye,"Liners - Banana, Paper",Crush - Cream Soda,Crackers Cheez It,Fondant - Icing
9,32785,Pail With Metal Handle 16l White,Wine - Redchard Merritt,Thermometer Digital,"Beef - Chuck, Boneless",Mayonnaise - Individual Pkg

#### cityblock

In [57]:
#Cambiado el metodo a cityblock
smatrix= squareform(pdist(datap.T, 'cityblock'))
distances = pd.DataFrame(1/(1 + smatrix), index=datap.columns, columns=datap.columns)

recomm = {customer: [] for customer in set(data['CustomerID'])}

for c_id in set(data['CustomerID']):
    similarities = distances[c_id].sort_values(ascending=False)[1:6].index
    similarities_data2 = data2[data2['CustomerID'].isin(similarities)].reset_index(drop=True)
    prod_sim = similarities_data2.groupby('ProductName').sum().sort_values('Quantity', ascending=False)['Quantity']
    merg = pd.merge(prod_sim, datap[c_id], on='ProductName').reset_index()
    merg.columns = ['ProductName', 'Quantity', 'Purchased'] 
    filt = merg.loc[merg['Purchased'] == 0]
    recomm[c_id] = list(filt['ProductName'].head())
    
#nuevo dataframe con el metodo nuevo
cityblock_recomm = pd.DataFrame.from_dict(recomm, orient='index').reset_index()
cityblock_recomm.columns = ['CustomerID', 'product1', 'product2', 'product3', 'product4', 'product5']
cityblock_recomm.head(10)

,CustomerID,product1,product2,product3,product4,product5
0,83973,"Pork - Bacon, Double Smoked","Nut - Chestnuts, Whole",Olive - Spread Tapenade,Butter - Unsalted,Beef Ground Medium
1,59399,"Pepper - Black, Whole",Soupfoamcont12oz 112con,"Pork - Bacon, Double Smoked",Soup - Campbells Bean Medley,"Salsify, Organic"
2,92168,Wine - Blue Nun Qualitatswein,Muffin Batt - Blueberry Passion,Knife Plastic - White,Chinese Foods - Chicken,"Wine - Magnotta, Merlot Sr Vqa"
3,49159,Wine - Blue Nun Qualitatswein,Butter - Unsalted,Tia Maria,Veal - Sweetbread,Wine - Chardonnay South
4,18441,Anchovy Paste - 56 G Tube,Flour - Pastry,Foam Cup 6 Oz,"Garlic - Primerba, Paste",Butter - Unsalted
5,22536,Knife Plastic - White,Cheese - Mozzarella,Butter - Unsalted,Sausage - Breakfast,"Beets - Candy Cane, Organic"
6,86028,"Sole - Dover, Whole, Fresh",Knife Plastic - White,Wine - Chardonnay South,Foam Dinner Plate,Sauce - Hollandaise
7,75791,Butter - Unsalted,Guinea Fowl,Berry Brulee,Ice Cream Bar - Hageen Daz To,Table Cloth 81x81 White
8,96272,Butter - Unsalted,"Pepper - Black, Whole",Knife Plastic - White,Sherry - Dry,Ecolab - Solid Fusion
9,32785,Soup - Campbells Bean Medley,Butter - Unsalted,"Pepper - Black, Whole",Ketchup - Tomato,Knife Plastic - White

#### cosine

In [59]:
#Cambiado el metodo a cosine
smatrix= squareform(pdist(datap.T, 'cosine'))
distances = pd.DataFrame(1/(1 + smatrix), index=datap.columns, columns=datap.columns)

recomm = {customer: [] for customer in set(data['CustomerID'])}

for c_id in set(data['CustomerID']):
    similarities = distances[c_id].sort_values(ascending=False)[1:6].index
    similarities_data2 = data2[data2['CustomerID'].isin(similarities)].reset_index(drop=True)
    prod_sim = similarities_data2.groupby('ProductName').sum().sort_values('Quantity', ascending=False)['Quantity']
    merg = pd.merge(prod_sim, datap[c_id], on='ProductName').reset_index()
    merg.columns = ['ProductName', 'Quantity', 'Purchased'] 
    filt = merg.loc[merg['Purchased'] == 0]
    recomm[c_id] = list(filt['ProductName'].head())
    
#nuevo dataframe con el metodo nuevo
cosine_recomm = pd.DataFrame.from_dict(recomm, orient='index').reset_index()
cosine_recomm.columns = ['CustomerID', 'product1', 'product2', 'product3', 'product4', 'product5']
cosine_recomm.head(10)

,CustomerID,product1,product2,product3,product4,product5
0,83973,Pastry - Choclate Baked,Flour - Pastry,Puree - Passion Fruit,Lettuce - Spring Mix,Broom - Corn
1,59399,Ezy Change Mophandle,Anchovy Paste - 56 G Tube,Garlic - Peeled,Broom - Corn,Water - Aquafina Vitamin
2,92168,Wiberg Super Cure,Tuna - Salad Premix,Sage - Ground,Apricots Fresh,Beef - Inside Round
3,49159,"Turnip - White, Organic",Peas - Frozen,Lamb - Ground,Beer - Blue,Beef - Ground Medium
4,18441,V8 - Berry Blend,Whmis - Spray Bottle Trigger,Mussels - Cultivated,Ecolab - Lime - A - Way 4/4 L,Milk - 2%
5,22536,Hersey Shakes,Muffin Batt - Choc Chk,Bread Crumbs - Panko,Spinach - Baby,Longos - Grilled Chicken With
6,86028,Mayonnaise - Individual Pkg,Pail With Metal Handle 16l White,Sunflower Seed Raw,Sausage - Breakfast,"Appetizer - Mini Egg Roll, Shrimp"
7,75791,Peas - Frozen,"Placemat - Scallop, White",Beef - Ground Medium,Milk - 2%,Sausage - Liver
8,96272,Crackers Cheez It,Fondant - Icing,Jolt Cola - Electric Blue,Lettuce - Spring Mix,Bread - Rye
9,32785,Wine - Redchard Merritt,Pail With Metal Handle 16l White,Thermometer Digital,Initation Crab Meat,Longos - Grilled Chicken With

#### jaccard

In [60]:
#Cambiado el metodo a cosine
smatrix= squareform(pdist(datap.T, 'jaccard'))
distances = pd.DataFrame(1/(1 + smatrix), index=datap.columns, columns=datap.columns)

recomm = {customer: [] for customer in set(data['CustomerID'])}

for c_id in set(data['CustomerID']):
    similarities = distances[c_id].sort_values(ascending=False)[1:6].index
    similarities_data2 = data2[data2['CustomerID'].isin(similarities)].reset_index(drop=True)
    prod_sim = similarities_data2.groupby('ProductName').sum().sort_values('Quantity', ascending=False)['Quantity']
    merg = pd.merge(prod_sim, datap[c_id], on='ProductName').reset_index()
    merg.columns = ['ProductName', 'Quantity', 'Purchased'] 
    filt = merg.loc[merg['Purchased'] == 0]
    recomm[c_id] = list(filt['ProductName'].head())
    
#nuevo dataframe con el metodo nuevo
jaccard_recomm = pd.DataFrame.from_dict(recomm, orient='index').reset_index()
jaccard_recomm.columns = ['CustomerID', 'product1', 'product2', 'product3', 'product4', 'product5']
jaccard_recomm.head(10)

,CustomerID,product1,product2,product3,product4,product5
0,83973,Towels - Paper / Kraft,Milk - 1%,"Chocolate - Semi Sweet, Calets",Pork - Belly Fresh,Bread Crumbs - Japanese Style
1,59399,"Beans - Kidney, Canned","Cheese - Brie, Triple Creme","Rum - Coconut, Malibu",Cheese - Parmesan Cubes,Gloves - Goldtouch Disposable
2,92168,Blackberries,Wiberg Super Cure,Salmon - Sockeye Raw,Cumin - Whole,Scallops - 10/20
3,49159,Flavouring - Orange,Cookie Dough - Double,Mussels - Cultivated,Cheese - Bocconcini,Macaroons - Two Bite Choc
4,18441,Bread Foccacia Whole,Macaroons - Two Bite Choc,Bread - English Muffin,"Juice - Cranberry, 341 Ml","Beef - Ground, Extra Lean, Fresh"
5,22536,Pants Custom Dry Clean,Cocktail Napkin Blue,Puree - Passion Fruit,Isomalt,"Nut - Pistachio, Shelled"
6,86028,Blueberries,Lettuce - Treviso,Bread - Calabrese Baguette,"Appetizer - Mini Egg Roll, Shrimp",Ice Cream Bar - Oreo Cone
7,75791,Beef - Top Sirloin - Aaa,Beer - Labatt Blue,Tia Maria,Sea Bass - Whole,Bread - English Muffin
8,96272,Knife Plastic - White,Vinegar - Sherry,Zucchini - Yellow,Langers - Ruby Red Grapfruit,Cookie Dough - Double
9,32785,Juice - Happy Planet,"Placemat - Scallop, White",Soup - Campbells Tomato Ravioli,Tomato - Tricolor Cherry,Chips Potato Salt Vinegar 43g