# Pandas Project Kathi Aparicio

In [1]:
import pandas as pd


df = pd.read_csv("attacks.csv",encoding='latin-1')
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
idx = df.index[df.isnull().all(1)]
nans = df.iloc[idx]
nans

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
8702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#se quiere elimar todas las filas que estan que contien valores null
dropfila = list(nans.index)
df1 = df.drop(dropfila)

In [4]:
df1

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Invertir las filas por columnas
df2=df1.T

In [6]:
df2

,0,1,2,3,4,5,6,7,8,9,...,8693,8694,8695,8696,8697,8698,8699,8700,8701,25722
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,0,0,0,0,0,0,0,0,0,xx
Date,25-Jun-2018,18-Jun-2018,09-Jun-2018,08-Jun-2018,04-Jun-2018,03-Jun-2018,03-Jun-2018,27-May-2018,26-May-2018,26-May-2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type,Boating,Unprovoked,Invalid,Unprovoked,Provoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,USA,USA,USA,AUSTRALIA,MEXICO,AUSTRALIA,BRAZIL,USA,USA,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area,California,Georgia,Hawaii,New South Wales,Colima,New South Wales,Pernambuco,Florida,Florida,Florida,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland,La Ticla,"Flat Rock, Ballina","Piedade Beach, Recife","Lighhouse Point Park, Ponce Inlet, Volusia County","Cocoa Beach, Brevard County","Daytona Beach, Volusia County",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Activity,Paddling,Standing,Surfing,Surfing,Free diving,Kite surfing,Swimming,Fishing,Walking,Standing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Name,Julie Wolfe,AdysonÂ McNeely,John Denges,male,Gustavo Ramos,Chris,Jose Ernesto da Silva,male,Cody High,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,F,F,M,M,M,M,M,M,M,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,57,11,48,NaN,NaN,NaN,18,52,15,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg,Lacerations to leg & hand shark PROVOKED INCIDENT,"No injury, board bitten",FATAL,Minor injury to foot. PROVOKED INCIDENT,Lower left leg bitten,Minor injury to foot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fatal (Y/N),N,N,N,N,N,N,Y,N,N,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,18h00,14h00 -15h00,07h45,NaN,NaN,NaN,Late afternoon,NaN,17h00,14h00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Species,White shark,NaN,NaN,2 m shark,"Tiger shark, 3m",NaN,Tiger shark,"Lemon shark, 3'","Bull shark, 6'",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF",A .Kipper,"Daily Telegraph, 6/4/2018","Diario de Pernambuco, 6/4/2018","K. McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","K. McMurray, Tracking Sharks.com",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf,2018.06.04-Ramos.pdf,2018.06.03.b-FlatRock.pdf,2018.06.03.a-daSilva.pdf,2018.05.27-Ponce.pdf,2018.05.26.b-High.pdf,2018.05.26.a-DaytonaBeach.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
href formula,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case Number.1,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case Number.2,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
original order,6303,6302,6301,6300,6299,6298,6297,6296,6295,6294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#ubicar las columnas con valores null
null_cols = df2.isnull().sum()
null_cols[null_cols > 0]

0         2
1         3
2         3
3         4
4         4
         ..
8698     23
8699     23
8700     23
8701     23
25722    23
Length: 8703, dtype: int64

In [8]:
#eliminar las columnas con valores NaN mayores o iguales a 23
drop_cols = list(null_cols[null_cols >= 23].index)
df3 = df2.drop(drop_cols, axis=1)

In [9]:
df3

,0,1,2,3,4,5,6,7,8,9,...,6299,6300,6301,6302,6303,6304,6305,6306,6307,6308
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,ND.0003,ND.0002,ND.0001,0,0,0,0,0,0,0
Date,25-Jun-2018,18-Jun-2018,09-Jun-2018,08-Jun-2018,04-Jun-2018,03-Jun-2018,03-Jun-2018,27-May-2018,26-May-2018,26-May-2018,...,1900-1905,1883-1889,1845-1853,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type,Boating,Unprovoked,Invalid,Unprovoked,Provoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,...,Unprovoked,Unprovoked,Unprovoked,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,USA,USA,USA,AUSTRALIA,MEXICO,AUSTRALIA,BRAZIL,USA,USA,USA,...,USA,PANAMA,CEYLON (SRI LANKA),NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area,California,Georgia,Hawaii,New South Wales,Colima,New South Wales,Pernambuco,Florida,Florida,Florida,...,North Carolina,NaN,Eastern Province,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland,La Ticla,"Flat Rock, Ballina","Piedade Beach, Recife","Lighhouse Point Park, Ponce Inlet, Volusia County","Cocoa Beach, Brevard County","Daytona Beach, Volusia County",...,Ocracoke Inlet,"Panama Bay 8ÂºN, 79ÂºW","Below the English fort, Trincomalee",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Activity,Paddling,Standing,Surfing,Surfing,Free diving,Kite surfing,Swimming,Fishing,Walking,Standing,...,Swimming,NaN,Swimming,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Name,Julie Wolfe,AdysonÂ McNeely,John Denges,male,Gustavo Ramos,Chris,Jose Ernesto da Silva,male,Cody High,male,...,Coast Guard personnel,Jules Patterson,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,F,F,M,M,M,M,M,M,M,M,...,M,M,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,57,11,48,NaN,NaN,NaN,18,52,15,12,...,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg,Lacerations to leg & hand shark PROVOKED INCIDENT,"No injury, board bitten",FATAL,Minor injury to foot. PROVOKED INCIDENT,Lower left leg bitten,Minor injury to foot,...,FATAL,FATAL,"FATAL. ""Shark bit him in half, carrying away t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fatal (Y/N),N,N,N,N,N,N,Y,N,N,N,...,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,18h00,14h00 -15h00,07h45,NaN,NaN,NaN,Late afternoon,NaN,17h00,14h00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Species,White shark,NaN,NaN,2 m shark,"Tiger shark, 3m",NaN,Tiger shark,"Lemon shark, 3'","Bull shark, 6'",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF",A .Kipper,"Daily Telegraph, 6/4/2018","Diario de Pernambuco, 6/4/2018","K. McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","K. McMurray, Tracking Sharks.com",...,"F. Schwartz, p.23; C. Creswell, GSAF","The Sun, 10/20/1938",S.W. Baker,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf,2018.06.04-Ramos.pdf,2018.06.03.b-FlatRock.pdf,2018.06.03.a-daSilva.pdf,2018.05.27-Ponce.pdf,2018.05.26.b-High.pdf,2018.05.26.a-DaytonaBeach.pdf,...,ND-0003-Ocracoke_1900-1905.pdf,ND-0002-JulesPatterson.pdf,ND-0001-Ceylon.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
href formula,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case Number.1,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,ND.0003,ND.0002,ND.0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case Number.2,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,ND.0003,ND.0002,ND.0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
original order,6303,6302,6301,6300,6299,6298,6297,6296,6295,6294,...,4,3,2,6304,6305,6306,6307,6308,6309,6310
Unnamed: 22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#ahora que puedo visualizar de mejor manera eliminarÃ© nuevamente pero ahora con columnas > a 20 (valores Nan)
drop_cols = list(null_cols[null_cols > 20].index)
df3 = df2.drop(drop_cols, axis=1)

In [11]:
df3

,0,1,2,3,4,5,6,7,8,9,...,6292,6293,6294,6295,6296,6297,6298,6299,6300,6301
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,ND.0010,ND.0009,ND.0008,ND.0007,ND.0006,ND.0005,ND.0004,ND.0003,ND.0002,ND.0001
Date,25-Jun-2018,18-Jun-2018,09-Jun-2018,08-Jun-2018,04-Jun-2018,03-Jun-2018,03-Jun-2018,27-May-2018,26-May-2018,26-May-2018,...,Circa 1862,Before 1906,Before 1906,Before 1906,Before 1906,Before 1903,Before 1903,1900-1905,1883-1889,1845-1853
Year,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,...,0,0,0,0,0,0,0,0,0,0
Type,Boating,Unprovoked,Invalid,Unprovoked,Provoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,...,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked
Country,USA,USA,USA,AUSTRALIA,MEXICO,AUSTRALIA,BRAZIL,USA,USA,USA,...,USA,AUSTRALIA,AUSTRALIA,AUSTRALIA,AUSTRALIA,AUSTRALIA,AUSTRALIA,USA,PANAMA,CEYLON (SRI LANKA)
Area,California,Georgia,Hawaii,New South Wales,Colima,New South Wales,Pernambuco,Florida,Florida,Florida,...,Hawaii,NaN,NaN,NaN,New South Wales,Western Australia,Western Australia,North Carolina,NaN,Eastern Province
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland,La Ticla,"Flat Rock, Ballina","Piedade Beach, Recife","Lighhouse Point Park, Ponce Inlet, Volusia County","Cocoa Beach, Brevard County","Daytona Beach, Volusia County",...,Puna,NaN,NaN,NaN,,Roebuck Bay,NaN,Ocracoke Inlet,"Panama Bay 8ÂºN, 79ÂºW","Below the English fort, Trincomalee"
Activity,Paddling,Standing,Surfing,Surfing,Free diving,Kite surfing,Swimming,Fishing,Walking,Standing,...,NaN,Fishing,Fishing,Fishing,Swimming,Diving,Pearl diving,Swimming,NaN,Swimming
Name,Julie Wolfe,AdysonÂ McNeely,John Denges,male,Gustavo Ramos,Chris,Jose Ernesto da Silva,male,Cody High,male,...,"A ""chiefess""",boy,fisherman,fisherman,Arab boy,male,Ahmun,Coast Guard personnel,Jules Patterson,male
Sex,F,F,M,M,M,M,M,M,M,M,...,F,M,M,M,M,M,M,M,M,M
Age,57,11,48,NaN,NaN,NaN,18,52,15,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg,Lacerations to leg & hand shark PROVOKED INCIDENT,"No injury, board bitten",FATAL,Minor injury to foot. PROVOKED INCIDENT,Lower left leg bitten,Minor injury to foot,...,Ankle bitten,"FATAL, knocked overboard by tail of shark & ca...",FATAL,FATAL,FATAL,FATAL,FATAL,FATAL,FATAL,"FATAL. ""Shark bit him in half, carrying away t..."
Fatal (Y/N),N,N,N,N,N,N,Y,N,N,N,...,N,Y,Y,Y,Y,Y,Y,Y,Y,Y
Time,18h00,14h00 -15h00,07h45,NaN,NaN,NaN,Late afternoon,NaN,17h00,14h00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Species,White shark,NaN,NaN,2 m shark,"Tiger shark, 3m",NaN,Tiger shark,"Lemon shark, 3'","Bull shark, 6'",NaN,...,NaN,Blue pointer,Blue pointer,Blue pointers,Said to involve a grey nurse shark that leapt ...,NaN,NaN,NaN,NaN,NaN
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF",A .Kipper,"Daily Telegraph, 6/4/2018","Diario de Pernambuco, 6/4/2018","K. McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","K. McMurray, Tracking Sharks.com",...,Captain W. Young,"NY Sun, 9/9/1906, referring to account by Loui...","NY Sun, 9/9/1906, referring to account by Loui...","NY Sun, 9/9/1906, referring to account by Loui...","L. Becke in New York Sun, 9/9/1906; L. Schultz...","H. Taunton; N. Bartlett, p. 234","H. Taunton; N. Bartlett, pp. 233-234","F. Schwartz, p.23; C. Creswell, GSAF","The Sun, 10/20/1938",S.W. Baker
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf,2018.06.04-Ramos.pdf,2018.06.03.b-FlatRock.pdf,2018.06.03.a-daSilva.pdf,2018.05.27-Ponce.pdf,2018.05.26.b-High.pdf,2018.05.26.a-DaytonaBeach.pdf,...,ND-0010-Puna Hawaii.pdf,ND-0009-boy-Australia.pdf,ND-0008-Fisherman2-Australia.pdf,ND-0007 - Fisherman-Australia.pdf,ND-0006-ArabBoy-Prymount.pdf,ND-0005-RoebuckBay.pdf,ND-0004-Ahmun.pdf,ND-0003-Ocracoke_1900-1905.pdf,ND-0002-JulesPatterson.pdf,ND-0001-Ceylon.pdf
href formula,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
Case Number.1,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,ND.0010,ND.0009,ND.0008,ND.0007,ND.0006,ND.0005,ND.0004,ND.0003,ND.0002,ND.0001
Case Number.2,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,ND.0010,ND.0009,ND.0008,ND.0007,ND.0006,ND.0005,ND.0004,ND.0003,ND.0002,ND.0001
original order,6303,6302,6301,6300,6299,6298,6297,6296,6295,6294,...,11,10,9,8,7,6,5,4,3,2
Unnamed: 22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#Realizo copia
df4 = df3.copy()

In [13]:
#Invierto Nuevamente mi DF 
df3=df3.T
df3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303,NaN,NaN
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302,NaN,NaN
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301,NaN,NaN
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300,NaN,NaN
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
6298,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
6299,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
6300,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
6301,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [14]:
#ahora procedo a realizar nuevamente la operacion para eliminar las columnas con valores Nan > a 20
df3

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303,NaN,NaN
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302,NaN,NaN
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301,NaN,NaN
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300,NaN,NaN
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
6298,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
6299,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
6300,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
6301,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [15]:
null_cols1 = df3.isnull().sum()
null_cols1[null_cols1 > 0]

Case Number                  1
Year                         2
Type                         4
Country                     50
Area                       455
Location                   540
Activity                   544
Name                       210
Sex                        565
Age                       2831
Injury                      28
Fatal (Y/N)                539
Time                      3354
Species                   2838
Investigator or Source      17
href formula                 1
Unnamed: 22               6301
Unnamed: 23               6300
dtype: int64

In [79]:
drop_cols2 = list(null_cols1[null_cols1 >= 6300].index)
df5 = df3.drop(drop_cols2, axis=1)

In [80]:
df5

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6
6298,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5
6299,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4
6300,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3
6301,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2

In [18]:
df4 = df5.copy
#df4 es una copia

In [81]:
df5 = df5.fillna(0)

In [82]:
df5

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,N,14h00 -15h00,0,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,0,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,0,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,0,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,0,0,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,0,Pearl diving,Ahmun,M,...,Y,0,0,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,0,"Panama Bay 8ÂºN, 79ÂºW",0,Jules Patterson,M,...,Y,0,0,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,0,0,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [83]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6302 entries, 0 to 6301
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             6302 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6302 non-null   float64
 3   Type                    6302 non-null   object
 4   Country                 6302 non-null   object
 5   Area                    6302 non-null   object
 6   Location                6302 non-null   object
 7   Activity                6302 non-null   object
 8   Name                    6302 non-null   object
 9   Sex                     6302 non-null   object
 10  Age                     6302 non-null   object
 11  Injury                  6302 non-null   object
 12  Fatal (Y/N)             6302 non-null   object
 13  Time                    6302 non-null   object
 14  Species                 6302 non-null   object
 15  Investigator or Source  6302 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6302 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6302 non-null   float64
dtypes: float64(2), object(20)
memory usage: 768.0+ KB

In [84]:
#Elimino las columnas Case Number.1 y Case Number.2 ya que contienen los mismos valores de Case Number
df5.drop(['Case Number.1','Case Number.2'],inplace = True, axis = 1)
df5

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,0,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,0,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,Minor injury to lower leg,N,0,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,0,Lacerations to leg & hand shark PROVOKED INCIDENT,N,0,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,0,Pearl diving,Ahmun,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,FATAL,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,0,"Panama Bay 8ÂºN, 79ÂºW",0,Jules Patterson,M,0,FATAL,Y,0,0,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,0,0,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2.0

In [23]:
df5.head(20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,0,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,0,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,Minor injury to lower leg,N,0,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,0,Lacerations to leg & hand shark PROVOKED INCIDENT,N,0,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,0,"No injury, board bitten",N,0,0,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6298.0
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6297.0
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,0,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6296.0
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6295.0
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,12,Minor injury to foot,N,14h00,0,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6294.0
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6293.0
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,10,Injuries to lower right leg and foot,N,0,0,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6292.0
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,10,Severe bite to right forearm,N,15h00,0,"C. Creswell, GSAF & K. McMurray TrackingSharks...",2018.05.13.b-Turrell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6291.0
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6290.0
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,34,Shallow lacerations to finger PROVOKED INCIDENT,N,0,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6289.0
15,2018.05.12,12-May-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,male,M,0,"Minor injury, marks on board",N,11h00,0,"B.Jacob, Dispatch Live, 5/12/2018",2018.05.12-EastLondon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6288.0
16,2018.05.09,09-May-2018,2018.0,Questionable,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,male,M,0,"No injury, surfboard damaged",N,10h30,Shark involvement not confirmed,"B. Myatt, GSAF",2018.05.09-SharpesBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6287.0
17,2018.04.30.R,Reported 30-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,female,M,0,Minor injury to ankle,N,0,0,"K. McMurray, TrackingSharks.com",2018.04.30.R-Thailand.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6286.0
18,2018.04.28.b,28-Apr-2018,2018.0,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,male,M,30,"No injury, shark bit scuba gear",N,10h40,Tiger shark,Costa Rica Star. 4/28/2018,2018.04.28.b-CostaRica.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6285.0
19,2018.04.28.a,28-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Gearys Beach,Surfing,Adam Murray,M,0,"No injury, knocked off board by shark",N,16h50,0,"B. Myatt, GSAF",2018.04.28.a-Murray.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6284.0

In [24]:
#Realizando un analisis de los campos Case Number y original order veo lo siguiente, en case number, muestra la fecha en la que se registrÃ³
#el caso, pero adicional ya existe el campo fecha(Date) puedo ver quÃ© si en un mismo dÃ­a hubo dos casos se registra uno como a y el siguiente como b
# y si uno sucediÃ³ dias antes pero se reportÃ¡ ese dia se agrega el valor R. 
# mi consideraciÃ³n es la siguiente como no muestra la fecha probable real de accidente si no que el registro en case number y date son iguales
# elminar el campo case number
#ahora para el campo original order, esta mostrado de manera desc la cantidad de casos que hay sÃ© puede decidir sÃ­, ordenar la data
#con la informaciÃ³n mas nueva Ã³ ordenarla desde la primer en original order(que serÃ­a el ataque mas antiguo registrado)

In [85]:
df6 = df5.sort_values('original order')
df6.head(10)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,0,0,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,0,"Panama Bay 8ÂºN, 79ÂºW",0,Jules Patterson,M,0,FATAL,Y,0,0,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,FATAL,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,0,Pearl diving,Ahmun,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5.0
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6.0
6296,ND.0006,Before 1906,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,0,FATAL,Y,0,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7.0
6295,ND.0007,Before 1906,0.0,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,FATAL,Y,0,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8.0
6294,ND.0008,Before 1906,0.0,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,FATAL,Y,0,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9.0
6293,ND.0009,Before 1906,0.0,Unprovoked,AUSTRALIA,0,0,Fishing,boy,M,0,"FATAL, knocked overboard by tail of shark & ca...",Y,0,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,10.0
6292,ND.0010,Circa 1862,0.0,Unprovoked,USA,Hawaii,Puna,0,"A ""chiefess""",F,0,Ankle bitten,N,0,0,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,11.0

In [26]:
#Ordenando de esta manera podemos observar que los primero ataques no tienen un registro valido para el campo date

In [86]:
df5.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,0,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,0,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,Minor injury to lower leg,N,0,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,0,Lacerations to leg & hand shark PROVOKED INCIDENT,N,0,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0

In [104]:
import re
df5['Date'].apply(lambda x: re.findall('\d{4}$', x))

0       [2018]
1       [2018]
2       [2018]
3       [2018]
4       [2018]
         ...
6297    [1903]
6298    [1903]
6299    [1905]
6300    [1889]
6301    [1853]
Name: Date, Length: 6302, dtype: object

In [88]:
df5['Year']= df5['Date'].apply(lambda x: re.findall('\d{4}$', x))

In [92]:
#Eliminar los corchetes que se agregaron en la columna Year
df5["Year"]=(df5["Year"].apply(lambda x: ",".join(x)))

In [93]:
df5

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,0,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,0,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,Minor injury to lower leg,N,0,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,0,Lacerations to leg & hand shark PROVOKED INCIDENT,N,0,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,1903,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6.0
6298,ND.0004,Before 1903,1903,Unprovoked,AUSTRALIA,Western Australia,0,Pearl diving,Ahmun,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5.0
6299,ND.0003,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,FATAL,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4.0
6300,ND.0002,1883-1889,1889,Unprovoked,PANAMA,0,"Panama Bay 8ÂºN, 79ÂºW",0,Jules Patterson,M,0,FATAL,Y,0,0,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3.0
6301,ND.0001,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,0,0,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2.0

In [94]:
#En vista que la columna Case Number no aporta informaciÃ³n se elimina
df5.drop(['Case Number'], axis = 'columns', inplace=True)

In [124]:
#Elimino la columna href, no aporta informaciÃ³n al igual que href formula y pdf
df5.drop(['href','href formula','pdf'], axis='columns', inplace=True)
df5

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,original order
0,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",6303.0
1,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,0,"K.McMurray, TrackingSharks.com",6302.0
2,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,0,"K.McMurray, TrackingSharks.com",6301.0
3,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,Minor injury to lower leg,N,0,2 m shark,"B. Myatt, GSAF",6300.0
4,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,0,Lacerations to leg & hand shark PROVOKED INCIDENT,N,0,"Tiger shark, 3m",A .Kipper,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,Before 1903,1903,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, p. 234",6.0
6298,Before 1903,1903,Unprovoked,AUSTRALIA,Western Australia,0,Pearl diving,Ahmun,M,0,FATAL,Y,0,0,"H. Taunton; N. Bartlett, pp. 233-234",5.0
6299,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,FATAL,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",4.0
6300,1883-1889,1889,Unprovoked,PANAMA,0,"Panama Bay 8ÂºN, 79ÂºW",0,Jules Patterson,M,0,FATAL,Y,0,0,"The Sun, 10/20/1938",3.0
6301,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,0,0,S.W. Baker,2.0

In [132]:
print(df5.Activity.value_counts())

Surfing                                                                971
Swimming                                                               869
0                                                                      544
Fishing                                                                431
Spearfishing                                                           333
                                                                      ...
His balloon crashed in the harbor                                        1
Swimming / floating on his back                                          1
Competing in a light tackle game fishing                                 1
Fishing from rocks, swept out to sea by large wave & treading water      1
Fell or jumped overboard from the liner Rhynland                         1
Name: Activity, Length: 1533, dtype: int64

In [150]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6302 entries, 0 to 6301
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    6302 non-null   object
 1   Year                    6302 non-null   object
 2   Type                    6302 non-null   object
 3   Country                 6302 non-null   object
 4   Area                    6302 non-null   object
 5   Location                6302 non-null   object
 6   Activity                6302 non-null   object
 7   Name                    6302 non-null   object
 8   Sex                     6302 non-null   object
 9   Age                     6302 non-null   object
 10  Injury                  6302 non-null   object
 11  Fatal (Y/N)             6302 non-null   object
 12  Time                    6302 non-null   object
 13  Species                 6302 non-null   object
 14  Investigator or Source  6302 non-null   object
 15  original order          6302 non-null   float64
dtypes: float64(1), object(15)
memory usage: 595.7+ KB

In [162]:
# OK.. el siguiente paso para limpiar mi data y tener informaciÃ³n mas consolidada, evaluando el count anterior es tomar solo las actividades con mas cantidad de registros
# Y omitiendo los que tienen valor 0, ya que en codigo mÃ¡s arriba se utilizÃ³ fillna y reemplazÃ³ Nan por cero
#Ademas para realizar algÃºn analisis no nos sirve no tener un registro sin la actividad que realizaba la persona

In [151]:
df5['Activity'] = df5['Activity'].astype('str')

In [177]:
df6 = df5[(df5['Activity'] == 'Surfing')|(df5['Activity'] == 'Swimming')|(df5['Activity'] == 'Fishing')|(df5['Activity'] == 'Spearfising')]

In [178]:
df6

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,original order
2,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,0,"K.McMurray, TrackingSharks.com",6301.0
3,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,Minor injury to lower leg,N,0,2 m shark,"B. Myatt, GSAF",6300.0
6,03-Jun-2018,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",6297.0
7,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,0,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",6296.0
12,13-May-2018,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,10,Severe bite to right forearm,N,15h00,0,"C. Creswell, GSAF & K. McMurray TrackingSharks...",6291.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6294,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,FATAL,Y,0,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",9.0
6295,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,FATAL,Y,0,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",8.0
6296,Before 1906,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,0,FATAL,Y,0,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",7.0
6299,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,FATAL,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",4.0
6301,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,0,0,S.W. Baker,2.0

In [163]:
#Ok en vista que el rango de fecha es bastante amplio y hay muchos registros donde no tengo su mes y dÃ­a, pero para todos tengo el aÃ±o
#los analisis que podrÃ­a realizar pueden ser por aÃ±os, tambiÃ©n tengo el campo Country y Area

In [164]:
#asi como en Activity harÃ© lo mismo para Injury

In [166]:
print(df6.Injury.value_counts())

FATAL                                                255
Foot bitten                                           47
Left foot bitten                                      30
Leg bitten                                            27
Right foot bitten                                     25
                                                    ...
Disappeared & his torn clothing washed ashore          1
Puncture wound on arm                                  1
Laceration & puncture wounds to right flank & hip      1
FATAL, leg severely bitten                             1
Cuts to dorsal surface of left foot                    1
Name: Injury, Length: 1418, dtype: int64

In [174]:
#"Ok en vista que en campo injury hay muchos fatal y los otros mayormente son leciones pero especifican el lugar de la lesiÃ³n, solo por 
#simplificar la columna y digamos de alguna manera limpiarla agregaremos una columna llamada Hurt donde solo encontraremos Fatal y Ijury
#Se va a eliminar la columna injury

In [179]:
df6['hurt'] = np.where(df6['Injury'].str.contains('FATAL', regex = False),'Fatal','Injury')
df6

<ipython-input-179-2763151f6e89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['hurt'] = np.where(df6['Injury'].str.contains('FATAL', regex = False),'Fatal','Injury')

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,original order,hurt
2,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,0,"K.McMurray, TrackingSharks.com",6301.0,Injury
3,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,Minor injury to lower leg,N,0,2 m shark,"B. Myatt, GSAF",6300.0,Injury
6,03-Jun-2018,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",6297.0,Fatal
7,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,0,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",6296.0,Injury
12,13-May-2018,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,10,Severe bite to right forearm,N,15h00,0,"C. Creswell, GSAF & K. McMurray TrackingSharks...",6291.0,Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6294,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,FATAL,Y,0,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",9.0,Fatal
6295,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,FATAL,Y,0,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",8.0,Fatal
6296,Before 1906,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,0,FATAL,Y,0,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",7.0,Fatal
6299,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,FATAL,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",4.0,Fatal
6301,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,0,0,S.W. Baker,2.0,Fatal

In [180]:
df6.drop(['Injury'], axis='columns', inplace=True)

C:\Users\Mercantil\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [181]:
df6

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Fatal (Y/N),Time,Species,Investigator or Source,original order,hurt
2,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,N,07h45,0,"K.McMurray, TrackingSharks.com",6301.0,Injury
3,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,N,0,2 m shark,"B. Myatt, GSAF",6300.0,Injury
6,03-Jun-2018,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",6297.0,Fatal
7,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,N,0,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",6296.0,Injury
12,13-May-2018,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,10,N,15h00,0,"C. Creswell, GSAF & K. McMurray TrackingSharks...",6291.0,Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6294,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,Y,0,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",9.0,Fatal
6295,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,Y,0,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",8.0,Fatal
6296,Before 1906,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,0,Y,0,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",7.0,Fatal
6299,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,Y,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",4.0,Fatal
6301,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,Y,0,0,S.W. Baker,2.0,Fatal

In [182]:
#Ahora evaluando lo que tengo veo que ya existÃ­a el campo fatal, pero... para que el esfuerzo valga la pena eliminarÃ© la columna fatal
#mantendrÃ© la nueva ya que con ella podemos sacar totales de cuantos son Fatal y cuantos Injury

In [183]:
df6.drop(['Fatal (Y/N)'], axis='columns', inplace=True)

C:\Users\Mercantil\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [184]:
#pasÃ© a otro DF para que no siguiera arrojando el error fatal
df7=df6

In [185]:
df7

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Time,Species,Investigator or Source,original order,hurt
2,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,0,"K.McMurray, TrackingSharks.com",6301.0,Injury
3,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,0,0,2 m shark,"B. Myatt, GSAF",6300.0,Injury
6,03-Jun-2018,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",6297.0,Fatal
7,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,0,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",6296.0,Injury
12,13-May-2018,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,10,15h00,0,"C. Creswell, GSAF & K. McMurray TrackingSharks...",6291.0,Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6294,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,0,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",9.0,Fatal
6295,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,0,0,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",8.0,Fatal
6296,Before 1906,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,0,0,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",7.0,Fatal
6299,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,0,0,"F. Schwartz, p.23; C. Creswell, GSAF",4.0,Fatal
6301,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,0,0,S.W. Baker,2.0,Fatal

In [188]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2271 entries, 2 to 6301
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    2271 non-null   object
 1   Year                    2271 non-null   object
 2   Type                    2271 non-null   object
 3   Country                 2271 non-null   object
 4   Area                    2271 non-null   object
 5   Location                2271 non-null   object
 6   Activity                2271 non-null   object
 7   Name                    2271 non-null   object
 8   Sex                     2271 non-null   object
 9   Age                     2271 non-null   object
 10  Time                    2271 non-null   object
 11  Species                 2271 non-null   object
 12  Investigator or Source  2271 non-null   object
 13  original order          2271 non-null   float64
 14  hurt                    2271 non-null   object
dtypes: float64(1), object(14)
memory usage: 159.7+ KB

In [190]:
print(df7.Age.value_counts())

0              797
17              89
16              73
18              73
15              65
              ...
5                1
?    &   14      1
50s              1
82               1
81               1
Name: Age, Length: 103, dtype: int64

In [191]:
#Ok analizando un poco esto... sabemos que la mayor cantidad de muertes es por gente surfiando, pero nuestra mayor cantidad de registros tienen valores 0
#recordando que anteriormente eran Nan
#ademas como ya tenemos las actividades a la hora de realizar un analisis podriamos poner rangos de edades promedio(pero eso serÃ­a ya en analisis)
#por lo tanto eliminarÃ© esta columna 
#Sigamos evaluando para hacer drop con mas columnas si es necesario
#La columna Investigator or Source no la concidero necesaria ya que es un estudio muy amplio y puede existir un investigador por caso
#Entonces no valdria la pena mantenerlo
#Time no tiene de igual forma valores que ayuden a un analisis

In [200]:
df7.drop(['Age','Investigator or Source','Time'], axis='columns', inplace=True)
df7

C:\Users\Mercantil\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Species,original order,hurt
2,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,0,6301.0,Injury
3,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,2 m shark,6300.0,Injury
6,03-Jun-2018,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,Tiger shark,6297.0,Fatal
7,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,"Lemon shark, 3'",6296.0,Injury
12,13-May-2018,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,0,6291.0,Injury
...,...,...,...,...,...,...,...,...,...,...,...,...
6294,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,Blue pointer,9.0,Fatal
6295,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,Blue pointers,8.0,Fatal
6296,Before 1906,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,Said to involve a grey nurse shark that leapt ...,7.0,Fatal
6299,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,4.0,Fatal
6301,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,0,2.0,Fatal

In [203]:
df7

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Species,original order,hurt
2,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,0,6301.0,Injury
3,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,2 m shark,6300.0,Injury
6,03-Jun-2018,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,Tiger shark,6297.0,Fatal
7,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,"Lemon shark, 3'",6296.0,Injury
12,13-May-2018,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,0,6291.0,Injury
...,...,...,...,...,...,...,...,...,...,...,...,...
6294,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,Blue pointer,9.0,Fatal
6295,Before 1906,1906,Unprovoked,AUSTRALIA,0,0,Fishing,fisherman,M,Blue pointers,8.0,Fatal
6296,Before 1906,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,Said to involve a grey nurse shark that leapt ...,7.0,Fatal
6299,1900-1905,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,0,4.0,Fatal
6301,1845-1853,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,0,2.0,Fatal

In [205]:
print(df7['Species '].value_counts())

0                                                                                             1010
White shark                                                                                     61
Shark involvement not confirmed                                                                 38
Tiger shark                                                                                     28
Shark involvement prior to death was not confirmed                                              23
                                                                                              ...
Bull shark, 2.5m                                                                                 1
Questionable incident; reported as shark attack but thought to involve a pinniped instead        1
7 shark's teeth found embedded in the woodwork of the boat                                       1
Possibly  a blacktip or spinner shark                                                            1
Said to involve a tiger shark or a hammerhead shark                                              1
Name: Species , Length: 660, dtype: int64

In [206]:
#ok con esto queria saber si valia la pena mantener la columna, pero en vista a que hay tantos valores Nan, es recomendable eliminar, de igual forma 
#sabemos que son ataques de tiburon 
#eliminaremos Date,Names y Species
#EliminarÃ© date ya que no tengo otro dato importante que extraer, ya tenemos el aÃ±o
#names, no es necesario

In [208]:
df7.drop(['Date','Name','Species '], axis='columns', inplace=True)
df7

C:\Users\Mercantil\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Year,Type,Country,Area,Location,Activity,Sex,original order,hurt
2,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,6301.0,Injury
3,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,6300.0,Injury
6,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,6297.0,Fatal
7,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,6296.0,Injury
12,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,M,6291.0,Injury
...,...,...,...,...,...,...,...,...,...
6294,1906,Unprovoked,AUSTRALIA,0,0,Fishing,M,9.0,Fatal
6295,1906,Unprovoked,AUSTRALIA,0,0,Fishing,M,8.0,Fatal
6296,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,M,7.0,Fatal
6299,1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,4.0,Fatal
6301,1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,2.0,Fatal

In [209]:
#type no aporta informaciÃ³n
df7.drop(['Type'], axis='columns', inplace=True)
df7

C:\Users\Mercantil\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Year,Country,Area,Location,Activity,Sex,original order,hurt
2,2018,USA,Hawaii,"Habush, Oahu",Surfing,M,6301.0,Injury
3,2018,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,6300.0,Injury
6,2018,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,6297.0,Fatal
7,2018,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,6296.0,Injury
12,2018,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,M,6291.0,Injury
...,...,...,...,...,...,...,...,...
6294,1906,AUSTRALIA,0,0,Fishing,M,9.0,Fatal
6295,1906,AUSTRALIA,0,0,Fishing,M,8.0,Fatal
6296,1906,AUSTRALIA,New South Wales,,Swimming,M,7.0,Fatal
6299,1905,USA,North Carolina,Ocracoke Inlet,Swimming,M,4.0,Fatal
6301,1853,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,2.0,Fatal

In [210]:
#Finalmente considero que tenemos una tabla bastante limpia y con datos relevante para un analisis

In [211]:
dffinal=df7
dffinal

,Year,Country,Area,Location,Activity,Sex,original order,hurt
2,2018,USA,Hawaii,"Habush, Oahu",Surfing,M,6301.0,Injury
3,2018,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,6300.0,Injury
6,2018,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,6297.0,Fatal
7,2018,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,6296.0,Injury
12,2018,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,M,6291.0,Injury
...,...,...,...,...,...,...,...,...
6294,1906,AUSTRALIA,0,0,Fishing,M,9.0,Fatal
6295,1906,AUSTRALIA,0,0,Fishing,M,8.0,Fatal
6296,1906,AUSTRALIA,New South Wales,,Swimming,M,7.0,Fatal
6299,1905,USA,North Carolina,Ocracoke Inlet,Swimming,M,4.0,Fatal
6301,1853,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,2.0,Fatal

In [212]:
dffinal.to_csv('Pandas_project.csv', header=True , index=False)

In [213]:
dffinal

,Year,Country,Area,Location,Activity,Sex,original order,hurt
2,2018,USA,Hawaii,"Habush, Oahu",Surfing,M,6301.0,Injury
3,2018,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,6300.0,Injury
6,2018,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,6297.0,Fatal
7,2018,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,6296.0,Injury
12,2018,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,M,6291.0,Injury
...,...,...,...,...,...,...,...,...
6294,1906,AUSTRALIA,0,0,Fishing,M,9.0,Fatal
6295,1906,AUSTRALIA,0,0,Fishing,M,8.0,Fatal
6296,1906,AUSTRALIA,New South Wales,,Swimming,M,7.0,Fatal
6299,1905,USA,North Carolina,Ocracoke Inlet,Swimming,M,4.0,Fatal
6301,1853,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,2.0,Fatal